EEEEEEEEEEE......EEEE.EEEEEEEEEEEEEE.E....EEEEEEEEEEEEEEEEEEEEEE...EEE/usr/lib/python3.4/site-packages/pisi/mirrors.py:39: ResourceWarning: unclosed file <_io.TextIOWrapper name='mirrors.conf' mode='r' encoding='UTF-8'>
  for line in open(config, "r").readlines():
.EEEEEEEEEE..EEEEEEEEE.F../media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/shelltest.py:37: ResourceWarning: unclosed file <_io.TextIOWrapper name='tests/echo-file' mode='r' encoding='UTF-8'>
  self.assertEqual(open('tests/echo-file').readlines()[0].strip(), 'eco subject')
/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/shelltest.py:39: ResourceWarning: unclosed file <_io.TextIOWrapper name='tests/echo-file' mode='r' encoding='UTF-8'>
  self.assertEqual(open('tests/echo-file').readlines()[1].strip(), 'subject eco')
...F..FEFEEEEEEEEEEEEEE...........F.....E...
======================================================================
ERROR: testMakeZip (archivetests.ArchiveTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/archivetests.py", line 43, in testMakeZip
    spec = SpecFile('repos/pardus-2007/system/base/openssl/pspec.xml')
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 327, in initialize
    init(self)
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 553, in init
    setattr(self, name, init_a())
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 694, in init
    return make_object()
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 690, in make_object
    obj.__init__(tag=tag, req=req)
TypeError: object.__init__() takes no parameters

======================================================================
ERROR: testTarUnpack (archivetests.ArchiveTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/archivetests.py", line 14, in testTarUnpack
    spec = SpecFile('repos/pardus-2007/system/base/curl/pspec.xml')
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 327, in initialize
    init(self)
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 553, in init
    setattr(self, name, init_a())
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 694, in init
    return make_object()
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 690, in make_object
    obj.__init__(tag=tag, req=req)
TypeError: object.__init__() takes no parameters

======================================================================
ERROR: testUnpackTarCond (archivetests.ArchiveTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/archivetests.py", line 23, in testUnpackTarCond
    spec = SpecFile('repos/pardus-2007/system/base/curl/pspec.xml')
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 327, in initialize
    init(self)
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 553, in init
    setattr(self, name, init_a())
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 694, in init
    return make_object()
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 690, in make_object
    obj.__init__(tag=tag, req=req)
TypeError: object.__init__() takes no parameters

======================================================================
ERROR: testZipUnpack (archivetests.ArchiveTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/archivetests.py", line 35, in testZipUnpack
    spec = SpecFile('repos/pardus-2007/system/base/openssl/pspec.xml')
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 327, in initialize
    init(self)
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 553, in init
    setattr(self, name, init_a())
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 694, in init
    return make_object()
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 690, in make_object
    obj.__init__(tag=tag, req=req)
TypeError: object.__init__() takes no parameters

======================================================================
ERROR: testGetComponent (database.componentdbtest.ComponentDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/componentdbtest.py", line 19, in setUp
    testcase.TestCase.setUp(self)
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testGetPackages (database.componentdbtest.ComponentDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/componentdbtest.py", line 19, in setUp
    testcase.TestCase.setUp(self)
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testGetUnionComponent (database.componentdbtest.ComponentDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/componentdbtest.py", line 19, in setUp
    testcase.TestCase.setUp(self)
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testGetUnionPackages (database.componentdbtest.ComponentDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/componentdbtest.py", line 19, in setUp
    testcase.TestCase.setUp(self)
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testHasComponent (database.componentdbtest.ComponentDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/componentdbtest.py", line 19, in setUp
    testcase.TestCase.setUp(self)
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testListComponents (database.componentdbtest.ComponentDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/componentdbtest.py", line 19, in setUp
    testcase.TestCase.setUp(self)
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testSearchComponent (database.componentdbtest.ComponentDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/componentdbtest.py", line 19, in setUp
    testcase.TestCase.setUp(self)
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testCalculateConflicts (conflicttests.ConflictTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/conflicttests.py", line 21, in testCalculateConflicts
    assert pisi.conflict.calculate_conflicts(packages, packagedb)
  File "/usr/lib/python3.4/site-packages/pisi/conflict.py", line 68, in calculate_conflicts
    pkg = packagedb.get_package(x)
  File "/usr/lib/python3.4/site-packages/pisi/db/packagedb.py", line 84, in get_package
    pkg, repo = self.get_package_repo(name, repo)
  File "/usr/lib/python3.4/site-packages/pisi/db/packagedb.py", line 157, in get_package_repo
    pkg, repo = self.pdb.get_item_repo(name, repo)
  File "/usr/lib/python3.4/site-packages/pisi/db/lazydb.py", line 116, in __getattr__
    self.__init()
  File "/usr/lib/python3.4/site-packages/pisi/db/lazydb.py", line 111, in __init
    self.init()
  File "/usr/lib/python3.4/site-packages/pisi/db/packagedb.py", line 42, in init
    for repo in repodb.list_repos():
TypeError: 'NoneType' object is not iterable

======================================================================
ERROR: testConflictCheck (conflicttests.ConflictTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/conflicttests.py", line 26, in testConflictCheck
    pisi.api.add_repo("repo1", "repos/repo1-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testInstalledPackageConflicts (conflicttests.ConflictTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/conflicttests.py", line 10, in testInstalledPackageConflicts
    pisi.api.install(["ethtool"])
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 465, in install
    pisi.db.historydb.HistoryDB().create_history("install")
  File "/usr/lib/python3.4/site-packages/pisi/db/historydb.py", line 32, in create_history
    self.history.create(operation)
  File "/usr/lib/python3.4/site-packages/pisi/db/lazydb.py", line 116, in __getattr__
    self.__init()
  File "/usr/lib/python3.4/site-packages/pisi/db/lazydb.py", line 111, in __init
    self.init()
  File "/usr/lib/python3.4/site-packages/pisi/db/historydb.py", line 22, in init
    self.__logs = self.__generate_history()
  File "/usr/lib/python3.4/site-packages/pisi/db/historydb.py", line 27, in __generate_history
    logs.sort(lambda x,y:int(x.split("_")[0]) - int(y.split("_")[0]))
TypeError: must use keyword argument for key function

======================================================================
ERROR: testInterRepoCrossConflicts (conflicttests.ConflictTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/conflicttests.py", line 44, in testInterRepoCrossConflicts
    pisi.api.add_repo("repo1", "repos/repo1-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testDictSatisfiesDep (dependencytest.DependencyTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/dependencytest.py", line 8, in testDictSatisfiesDep
    pisi.api.install(["ethtool"])
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 465, in install
    pisi.db.historydb.HistoryDB().create_history("install")
  File "/usr/lib/python3.4/site-packages/pisi/db/historydb.py", line 32, in create_history
    self.history.create(operation)
  File "/usr/lib/python3.4/site-packages/pisi/db/lazydb.py", line 116, in __getattr__
    self.__init()
  File "/usr/lib/python3.4/site-packages/pisi/db/lazydb.py", line 111, in __init
    self.init()
  File "/usr/lib/python3.4/site-packages/pisi/db/historydb.py", line 22, in init
    self.__logs = self.__generate_history()
  File "/usr/lib/python3.4/site-packages/pisi/db/historydb.py", line 27, in __generate_history
    logs.sort(lambda x,y:int(x.split("_")[0]) - int(y.split("_")[0]))
TypeError: must use keyword argument for key function

======================================================================
ERROR: testInstalledSatisfiesDep (dependencytest.DependencyTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/dependencytest.py", line 23, in testInstalledSatisfiesDep
    pisi.api.install(["ctorrent"])
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 465, in install
    pisi.db.historydb.HistoryDB().create_history("install")
  File "/usr/lib/python3.4/site-packages/pisi/db/historydb.py", line 32, in create_history
    self.history.create(operation)
  File "/usr/lib/python3.4/site-packages/pisi/db/lazydb.py", line 116, in __getattr__
    self.__init()
  File "/usr/lib/python3.4/site-packages/pisi/db/lazydb.py", line 111, in __init
    self.init()
  File "/usr/lib/python3.4/site-packages/pisi/db/historydb.py", line 22, in init
    self.__logs = self.__generate_history()
  File "/usr/lib/python3.4/site-packages/pisi/db/historydb.py", line 27, in __generate_history
    logs.sort(lambda x,y:int(x.split("_")[0]) - int(y.split("_")[0]))
TypeError: must use keyword argument for key function

======================================================================
ERROR: testRepoSatisfiesDependency (dependencytest.DependencyTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/dependencytest.py", line 30, in testRepoSatisfiesDependency
    pisi.api.install(["ethtool"])
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 465, in install
    pisi.db.historydb.HistoryDB().create_history("install")
  File "/usr/lib/python3.4/site-packages/pisi/db/historydb.py", line 32, in create_history
    self.history.create(operation)
  File "/usr/lib/python3.4/site-packages/pisi/db/lazydb.py", line 116, in __getattr__
    self.__init()
  File "/usr/lib/python3.4/site-packages/pisi/db/lazydb.py", line 111, in __init
    self.init()
  File "/usr/lib/python3.4/site-packages/pisi/db/historydb.py", line 22, in init
    self.__logs = self.__generate_history()
  File "/usr/lib/python3.4/site-packages/pisi/db/historydb.py", line 27, in __generate_history
    logs.sort(lambda x,y:int(x.split("_")[0]) - int(y.split("_")[0]))
TypeError: must use keyword argument for key function

======================================================================
ERROR: testFetch (fetchtest.FetchTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/fetchtest.py", line 15, in setUp
    self.spec = SpecFile()
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 327, in initialize
    init(self)
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 553, in init
    setattr(self, name, init_a())
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 694, in init
    return make_object()
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 690, in make_object
    obj.__init__(tag=tag, req=req)
TypeError: object.__init__() takes no parameters

======================================================================
ERROR: testFetcherFunctions (fetchtest.FetchTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/fetchtest.py", line 15, in setUp
    self.spec = SpecFile()
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 327, in initialize
    init(self)
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 553, in init
    setattr(self, name, init_a())
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 694, in init
    return make_object()
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 690, in make_object
    obj.__init__(tag=tag, req=req)
TypeError: object.__init__() takes no parameters

======================================================================
ERROR: testChooseMethod (filetest.FileTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/filetest.py", line 17, in testChooseMethod
    compress = File('repos/contrib-2007/pisi-index.xml', File.read)
  File "/usr/lib/python3.4/site-packages/pisi/file.py", line 205, in __init__
    self.__file__ = file(localfile, access)
NameError: name 'file' is not defined

======================================================================
ERROR: testDecompress (filetest.FileTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/filetest.py", line 21, in testDecompress
    localfile = File('repos/pardus-2007/system/base/curl/pspec.xml', File.read)
  File "/usr/lib/python3.4/site-packages/pisi/file.py", line 205, in __init__
    self.__file__ = file(localfile, access)
NameError: name 'file' is not defined

======================================================================
ERROR: testLocalFile (filetest.FileTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/filetest.py", line 26, in testLocalFile
    f = File('repos/pardus-2007/system/base/curl/pspec.xml', File.read)
  File "/usr/lib/python3.4/site-packages/pisi/file.py", line 205, in __init__
    self.__file__ = file(localfile, access)
NameError: name 'file' is not defined

======================================================================
ERROR: testMakeUri (filetest.FileTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/filetest.py", line 12, in testMakeUri
    spec = SpecFile("repos/pardus-2007/system/base/curl/pspec.xml")
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 327, in initialize
    init(self)
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 553, in init
    setattr(self, name, init_a())
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 694, in init
    return make_object()
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 690, in make_object
    obj.__init__(tag=tag, req=req)
TypeError: object.__init__() takes no parameters

======================================================================
ERROR: testRemoteRead (filetest.FileTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/pisi/fetcher.py", line 145, in fetch
    import urlgrabber
ImportError: No module named 'urlgrabber'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/filetest.py", line 31, in testRemoteRead
    f = File('http://www.pardus.org.tr/urunler/pardus-2009.2-Geronticus_eremita-surum-notlari-tr.html', File.read)
  File "/usr/lib/python3.4/site-packages/pisi/file.py", line 193, in __init__
    localfile = File.download(uri, transfer_dir, sha1sum, compress, sign)
  File "/usr/lib/python3.4/site-packages/pisi/file.py", line 137, in download
    pisi.fetcher.fetch_url(uri, transfer_dir, ctx.ui.Progress, tmpfile)
  File "/usr/lib/python3.4/site-packages/pisi/fetcher.py", line 245, in fetch_url
    fetch.fetch()
  File "/usr/lib/python3.4/site-packages/pisi/fetcher.py", line 147, in fetch
    raise FetchError(_('Urlgrabber needs to be installed to run this command'))
pisi.fetcher.FetchError: Bu komutun çalıştırılabilmesi için Urlgrabber kurulu olmalı.

======================================================================
ERROR: testAddRemoveFiles (database.filesdbtest.FilesDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testGetFile (database.filesdbtest.FilesDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testHasFile (database.filesdbtest.FilesDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testSearchFile (database.filesdbtest.FilesDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testFiles (filestest.FilesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/pisi/pxml/xmlfile.py", line 84, in readxml
    self.doc = iks.parse(localpath)
FileNotFoundError: [Errno 2] No such file or directory: 'repos/pardus-2007/system/base/curl/pspec.xml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/filestest.py", line 18, in testFiles
    self.files.read('repos/pardus-2007/system/base/curl/pspec.xml')
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 443, in read
    compress=compress, sign=sign, copylocal=copylocal)
  File "/usr/lib/python3.4/site-packages/pisi/pxml/xmlfile.py", line 87, in readxml
    raise Error(_("Unable to read file (%s): %s") %(localpath,e))
pisi.pxml.xmlfile.Error: Dosya okunamadı (repos/pardus-2007/system/base/curl/pspec.xml): [Errno 2] No such file or directory: 'repos/pardus-2007/system/base/curl/pspec.xml'

======================================================================
ERROR: testCreate (historytest.HistoryTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/historytest.py", line 7, in testCreate
    history = pisi.history.History()
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 327, in initialize
    init(self)
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 553, in init
    setattr(self, name, init_a())
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 694, in init
    return make_object()
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 690, in make_object
    obj.__init__(tag=tag, req=req)
TypeError: object.__init__() takes no parameters

======================================================================
ERROR: testGetLatest (historytest.HistoryTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/historytest.py", line 14, in testGetLatest
    history = pisi.history.History()
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 327, in initialize
    init(self)
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 553, in init
    setattr(self, name, init_a())
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 694, in init
    return make_object()
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 690, in make_object
    obj.__init__(tag=tag, req=req)
TypeError: object.__init__() takes no parameters

======================================================================
ERROR: testAddRemovePackage (database.installdbtest.InstallDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/installdbtest.py", line 19, in setUp
    testcase.TestCase.setUp(self)
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testClearPending (database.installdbtest.InstallDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/installdbtest.py", line 19, in setUp
    testcase.TestCase.setUp(self)
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testGetFiles (database.installdbtest.InstallDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/installdbtest.py", line 19, in setUp
    testcase.TestCase.setUp(self)
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testGetInfo (database.installdbtest.InstallDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/installdbtest.py", line 19, in setUp
    testcase.TestCase.setUp(self)
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testGetPackage (database.installdbtest.InstallDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/installdbtest.py", line 19, in setUp
    testcase.TestCase.setUp(self)
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testGetReverseDependencies (database.installdbtest.InstallDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/installdbtest.py", line 19, in setUp
    testcase.TestCase.setUp(self)
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testGetVersion (database.installdbtest.InstallDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/installdbtest.py", line 19, in setUp
    testcase.TestCase.setUp(self)
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testHasPackage (database.installdbtest.InstallDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/installdbtest.py", line 19, in setUp
    testcase.TestCase.setUp(self)
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testListInstalled (database.installdbtest.InstallDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/installdbtest.py", line 19, in setUp
    testcase.TestCase.setUp(self)
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testMarkListPending (database.installdbtest.InstallDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/installdbtest.py", line 19, in setUp
    testcase.TestCase.setUp(self)
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testSearchPackage (database.installdbtest.InstallDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/installdbtest.py", line 19, in setUp
    testcase.TestCase.setUp(self)
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testGetItem (database.itembyrepotest.ItemByRepoTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testGetItemAndRepository (database.itembyrepotest.ItemByRepoTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testGetItemKeys (database.itembyrepotest.ItemByRepoTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testGetItemOfRepository (database.itembyrepotest.ItemByRepoTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testGetListItem (database.itembyrepotest.ItemByRepoTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testHasItem (database.itembyrepotest.ItemByRepoTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testHasRepository (database.itembyrepotest.ItemByRepoTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testItemRepos (database.itembyrepotest.ItemByRepoTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testWhichRepo (database.itembyrepotest.ItemByRepoTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testRead (metadatatest.MetadataTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/metadatatest.py", line 10, in testRead
    md = metadata.MetaData()
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 327, in initialize
    init(self)
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 553, in init
    setattr(self, name, init_a())
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 694, in init
    return make_object()
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 690, in make_object
    obj.__init__(tag=tag, req=req)
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 327, in initialize
    init(self)
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 553, in init
    setattr(self, name, init_a())
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 694, in init
    return make_object()
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 690, in make_object
    obj.__init__(tag=tag, req=req)
TypeError: object.__init__() takes no parameters

======================================================================
ERROR: testVerify (metadatatest.MetadataTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/metadatatest.py", line 18, in testVerify
    md = self.testRead()
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/metadatatest.py", line 10, in testRead
    md = metadata.MetaData()
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 327, in initialize
    init(self)
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 553, in init
    setattr(self, name, init_a())
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 694, in init
    return make_object()
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 690, in make_object
    obj.__init__(tag=tag, req=req)
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 327, in initialize
    init(self)
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 553, in init
    setattr(self, name, init_a())
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 694, in init
    return make_object()
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 690, in make_object
    obj.__init__(tag=tag, req=req)
TypeError: object.__init__() takes no parameters

======================================================================
ERROR: testWrite (metadatatest.MetadataTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/metadatatest.py", line 23, in testWrite
    md = self.testRead()
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/metadatatest.py", line 10, in testRead
    md = metadata.MetaData()
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 327, in initialize
    init(self)
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 553, in init
    setattr(self, name, init_a())
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 694, in init
    return make_object()
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 690, in make_object
    obj.__init__(tag=tag, req=req)
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 327, in initialize
    init(self)
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 553, in init
    setattr(self, name, init_a())
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 694, in init
    return make_object()
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 690, in make_object
    obj.__init__(tag=tag, req=req)
TypeError: object.__init__() takes no parameters

======================================================================
ERROR: testGetObsoletes (database.packagedbtest.PackageDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/packagedbtest.py", line 19, in setUp
    testcase.TestCase.setUp(self)
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testGetPackage (database.packagedbtest.PackageDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/packagedbtest.py", line 19, in setUp
    testcase.TestCase.setUp(self)
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testGetPackageAndRepository (database.packagedbtest.PackageDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/packagedbtest.py", line 19, in setUp
    testcase.TestCase.setUp(self)
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testGetReplaces (database.packagedbtest.PackageDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/packagedbtest.py", line 19, in setUp
    testcase.TestCase.setUp(self)
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testGetReverseDependencies (database.packagedbtest.PackageDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/packagedbtest.py", line 19, in setUp
    testcase.TestCase.setUp(self)
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testGetVersion (database.packagedbtest.PackageDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/packagedbtest.py", line 19, in setUp
    testcase.TestCase.setUp(self)
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testHasPackage (database.packagedbtest.PackageDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/packagedbtest.py", line 19, in setUp
    testcase.TestCase.setUp(self)
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testListPackages (database.packagedbtest.PackageDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/packagedbtest.py", line 19, in setUp
    testcase.TestCase.setUp(self)
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testSearchPackage (database.packagedbtest.PackageDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/packagedbtest.py", line 19, in setUp
    testcase.TestCase.setUp(self)
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testWhichRepo (database.packagedbtest.PackageDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/packagedbtest.py", line 19, in setUp
    testcase.TestCase.setUp(self)
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testInstalledPackageSatisfies (relationtest.RelationTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/relationtest.py", line 7, in testInstalledPackageSatisfies
    pisi.api.install(["ethtool"])
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 465, in install
    pisi.db.historydb.HistoryDB().create_history("install")
  File "/usr/lib/python3.4/site-packages/pisi/db/historydb.py", line 32, in create_history
    self.history.create(operation)
  File "/usr/lib/python3.4/site-packages/pisi/db/lazydb.py", line 116, in __getattr__
    self.__init()
  File "/usr/lib/python3.4/site-packages/pisi/db/lazydb.py", line 111, in __init
    self.init()
  File "/usr/lib/python3.4/site-packages/pisi/db/historydb.py", line 22, in init
    self.__logs = self.__generate_history()
  File "/usr/lib/python3.4/site-packages/pisi/db/historydb.py", line 27, in __generate_history
    logs.sort(lambda x,y:int(x.split("_")[0]) - int(y.split("_")[0]))
TypeError: must use keyword argument for key function

======================================================================
ERROR: testInstalledPackageReplaced (replacetest.ReplaceTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/replacetest.py", line 7, in testInstalledPackageReplaced
    pisi.api.install(["ethtool"])
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 465, in install
    pisi.db.historydb.HistoryDB().create_history("install")
  File "/usr/lib/python3.4/site-packages/pisi/db/historydb.py", line 32, in create_history
    self.history.create(operation)
  File "/usr/lib/python3.4/site-packages/pisi/db/lazydb.py", line 116, in __getattr__
    self.__init()
  File "/usr/lib/python3.4/site-packages/pisi/db/lazydb.py", line 111, in __init
    self.init()
  File "/usr/lib/python3.4/site-packages/pisi/db/historydb.py", line 22, in init
    self.__logs = self.__generate_history()
  File "/usr/lib/python3.4/site-packages/pisi/db/historydb.py", line 27, in __generate_history
    logs.sort(lambda x,y:int(x.split("_")[0]) - int(y.split("_")[0]))
TypeError: must use keyword argument for key function

======================================================================
ERROR: testAddRemoveCycle (database.repodbtest.RepoDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/repodbtest.py", line 19, in setUp
    testcase.TestCase.setUp(self)
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testAddRemoveRepo (database.repodbtest.RepoDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/repodbtest.py", line 19, in setUp
    testcase.TestCase.setUp(self)
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testGetBinaryRepos (database.repodbtest.RepoDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/repodbtest.py", line 19, in setUp
    testcase.TestCase.setUp(self)
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testGetRepo (database.repodbtest.RepoDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/repodbtest.py", line 19, in setUp
    testcase.TestCase.setUp(self)
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testGetSourceRepos (database.repodbtest.RepoDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/repodbtest.py", line 19, in setUp
    testcase.TestCase.setUp(self)
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testListRepos (database.repodbtest.RepoDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/repodbtest.py", line 19, in setUp
    testcase.TestCase.setUp(self)
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testRepoOrder (database.repodbtest.RepoDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/repodbtest.py", line 19, in setUp
    testcase.TestCase.setUp(self)
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testSystem (shelltest.ShellTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/shelltest.py", line 114, in testSystem
    system('touch tests/systemtest')
  File "/usr/lib/python3.4/site-packages/pisi/actionsapi/shelltools.py", line 250, in system
    command = bytes.join(bytes.split(command))
TypeError: descriptor 'split' requires a 'bytes' object but received a 'str'

======================================================================
ERROR: testFetch (srcarchivetest.SourceArchiveTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/srcarchivetest.py", line 8, in testFetch
    spec = SpecFile('repos/pardus-2007/system/base/curl/pspec.xml')
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 327, in initialize
    init(self)
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 553, in init
    setattr(self, name, init_a())
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 694, in init
    return make_object()
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 690, in make_object
    obj.__init__(tag=tag, req=req)
TypeError: object.__init__() takes no parameters

======================================================================
ERROR: testIscached (srcarchivetest.SourceArchiveTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/srcarchivetest.py", line 18, in testIscached
    spec = SpecFile('repos/pardus-2007/system/base/curl/pspec.xml')
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 327, in initialize
    init(self)
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 553, in init
    setattr(self, name, init_a())
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 694, in init
    return make_object()
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 690, in make_object
    obj.__init__(tag=tag, req=req)
TypeError: object.__init__() takes no parameters

======================================================================
ERROR: testUnpack (srcarchivetest.SourceArchiveTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/srcarchivetest.py", line 24, in testUnpack
    spec = SpecFile('repos/pardus-2007/system/base/curl/pspec.xml')
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 327, in initialize
    init(self)
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 553, in init
    setattr(self, name, init_a())
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 694, in init
    return make_object()
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 690, in make_object
    obj.__init__(tag=tag, req=req)
TypeError: object.__init__() takes no parameters

======================================================================
ERROR: testGetSourceFromPackage (database.sourcedbtest.SourceDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/sourcedbtest.py", line 19, in setUp
    testcase.TestCase.setUp(self)
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testGetSpec (database.sourcedbtest.SourceDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/sourcedbtest.py", line 19, in setUp
    testcase.TestCase.setUp(self)
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testGetSpecAndRepository (database.sourcedbtest.SourceDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/sourcedbtest.py", line 19, in setUp
    testcase.TestCase.setUp(self)
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testGetSpecOfRepository (database.sourcedbtest.SourceDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/sourcedbtest.py", line 19, in setUp
    testcase.TestCase.setUp(self)
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testHasSpec (database.sourcedbtest.SourceDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/sourcedbtest.py", line 19, in setUp
    testcase.TestCase.setUp(self)
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testListSources (database.sourcedbtest.SourceDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/sourcedbtest.py", line 19, in setUp
    testcase.TestCase.setUp(self)
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testSearchPackage (database.sourcedbtest.SourceDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/sourcedbtest.py", line 19, in setUp
    testcase.TestCase.setUp(self)
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/database/testcase.py", line 18, in setUp
    pisi.api.add_repo("pardus-2007", "repos/pardus-2007-bin/pisi-index.xml")
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 69, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python3.4/site-packages/pisi/api.py", line 797, in add_repo
    if repodb.has_repo(name):
  File "/usr/lib/python3.4/site-packages/pisi/db/repodb.py", line 148, in has_repo
    return name in self.list_repos(only_active=False)
TypeError: argument of type 'NoneType' is not iterable

======================================================================
ERROR: testCopy (specfiletests.SpecFileTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/specfiletests.py", line 8, in setUp
    self.spec = specfile.SpecFile()
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 327, in initialize
    init(self)
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 553, in init
    setattr(self, name, init_a())
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 694, in init
    return make_object()
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 690, in make_object
    obj.__init__(tag=tag, req=req)
TypeError: object.__init__() takes no parameters

======================================================================
ERROR: testGetSourceRelease (specfiletests.SpecFileTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/specfiletests.py", line 8, in setUp
    self.spec = specfile.SpecFile()
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 327, in initialize
    init(self)
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 553, in init
    setattr(self, name, init_a())
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 694, in init
    return make_object()
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 690, in make_object
    obj.__init__(tag=tag, req=req)
TypeError: object.__init__() takes no parameters

======================================================================
ERROR: testGetSourceVersion (specfiletests.SpecFileTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/specfiletests.py", line 8, in setUp
    self.spec = specfile.SpecFile()
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 327, in initialize
    init(self)
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 553, in init
    setattr(self, name, init_a())
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 694, in init
    return make_object()
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 690, in make_object
    obj.__init__(tag=tag, req=req)
TypeError: object.__init__() takes no parameters

======================================================================
ERROR: testVerify (specfiletests.SpecFileTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/specfiletests.py", line 8, in setUp
    self.spec = specfile.SpecFile()
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 327, in initialize
    init(self)
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 553, in init
    setattr(self, name, init_a())
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 694, in init
    return make_object()
  File "/usr/lib/python3.4/site-packages/pisi/pxml/autoxml.py", line 690, in make_object
    obj.__init__(tag=tag, req=req)
TypeError: object.__init__() takes no parameters

======================================================================
ERROR: testOpsCharacters (versiontest.VersionTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/versiontest.py", line 66, in testOpsCharacters
    self.assertTrue(v1 > v2)
  File "/usr/lib/python3.4/site-packages/pisi/version.py", line 107, in __gt__
    return self.__version > rhs.__version
TypeError: unorderable types: str() > NoneType()

======================================================================
FAIL: testCanAccessDirectory (shelltest.ShellTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/shelltest.py", line 21, in testCanAccessDirectory
    assert can_access_directory('/boot')
AssertionError

======================================================================
FAIL: testIsLink (shelltest.ShellTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/shelltest.py", line 80, in testIsLink
    assert isLink('tests/history')
AssertionError

======================================================================
FAIL: testSym (shelltest.ShellTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/shelltest.py", line 47, in testSym
    self.assertEqual(os.path.islink('tests/repos'),True)
AssertionError: False != True

======================================================================
FAIL: testUnlinkDir (shelltest.ShellTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/shelltest.py", line 56, in testUnlinkDir
    self.assertEqual(os.path.islink('tests/history'), True)
AssertionError: False != True

======================================================================
FAIL: testRunBatch (utiltest.UtilTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/suleyman/YAZILIM/AquilaNipalensis/package-manager/tests/utiltest.py", line 13, in testRunBatch
    assert (0, '', '') == run_batch('cd')
AssertionError

----------------------------------------------------------------------
Ran 140 tests in 45.496s

FAILED (failures=5, errors=90)
